autoload, "yak.i",
    yak_shutdown,
    yak_start,
    yak_get_server_port,
    yak_get_value,
    yak_to_text,
    yak_connect,
    yak_send,
    yak_send_message,
    yak_recv_message,
    yak_info;
